CREATE TABLE catalogs (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  catalog_name TEXT NOT NULL
);
CREATE TABLE conversations (
  id SERIAL PRIMARY KEY,
  participants INT[] NOT NULL,
  black_list BOOLEAN[] NOT NULL,
  favorite_list BOOLEAN[] NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE catalogs_to_conversations (
  catalog_id INT NOT NULL REFERENCES catalogs (id) ON DELETE CASCADE ON UPDATE CASCADE,
  conversation_id INT NOT NULL REFERENCES conversations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (catalog_id, conversation_id)
);
CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  sender INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  body TEXT NOT NULL,
  conversation INT NOT NULL REFERENCES conversations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);