CREATE TABLE Catalogs (
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  catalogName VARCHAR(255) NOT NULL
);
CREATE TABLE Conversations (
  id SERIAL PRIMARY KEY,
  participant1 INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  participant2 INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  blackList1 BOOLEAN NOT NULL,
  blackList2 BOOLEAN NOT NULL,
  favoriteList1 BOOLEAN NOT NULL,
  favoriteList2 BOOLEAN NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Chats (
  catalogId INT NOT NULL REFERENCES Catalogs(id) ON DELETE CASCADE ON UPDATE CASCADE,
  conversationId INT NOT NULL REFERENCES Conversations(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (catalogId, conversationId)
);
CREATE TABLE Messages (
  id SERIAL PRIMARY KEY,
  sender INT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  body TEXT NOT NULL,
  "conversation" INT NOT NULL REFERENCES Conversations(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE Catalogs, Conversations, Chats, Messages;